### ISSUE TITLE
Very difficult to understand, there is a 'curse' in this sentence! Solution is much worse!

### ISSUE THREAD

**Issue by seyma-tas** [learn-co-curriculum/dsc-curse-of-dimensionality-lab#1]
To examine the curse of dimensionality, you'll investigate the average distance to the center of n-dimensional space. As you'll see, this average distance increases as the number of dimensions increases. To investigate this, generate 100 random points for various n-dimensional spaces. Investigate n-dimensional spaces from n=1 to n=1000. In each of these, construct the 100 random points using a random number between -10 and 10 for each dimension of the point. From there, calculate the average distance from each of these points to the origin. Finally, plot this relationship on a graph; the x-axis will be n, the number of dimensions, and the y-axis will be the average distance from the origin.

To understand this loop:
avg_distances = []
for n in range(1, 1001):
    avg_distances.append(np.mean([euclidean_distance(np.random.uniform(low=-10, high=10, size=n), [0 for i in range(n)]) for p in range(100)]))

I wrote this loop:

avg_distances = []
for n in range(1, 1001):
    print('n:', n)
    p1 = np.random.uniform(low=-10, high=10, size=n)
    print(p1)
    p2 = [0 for i in range(n)]
    print(p2)
    distance = np.mean([euclidean_distance(p1 ,p2) for p in range(100)])
    print(distance)
    avg_distances.append(distance)

**Comment by jessepisel** [comment]
Thanks for the feedback @seyma-tas :wave:. 

I agree that the solution for that example is rather difficult to understand. I really like how you reimplemented it so that each line has a specific goal. This makes it much more readable. I have implemented your changes in commit 1be14d995b53a2e81c742b120082de3289862f4c.

I am closing this issue at this time.
